services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma

    restart: unless-stopped

    user: "1000:1000"

    security_opt:
      - no-new-privileges:true

    mem_limit: 512m
    mem_reservation: 128m
    pids_limit: 128

    volumes:
      - uptime-kuma-data:/app/data

    ports:
      - "3001:3001"

volumes:
  uptime-kuma-data:
